const topics = JSON.parse(`[
    {"username":"Hoang Quoc Viet","type":"Guitar","topic":"Tư vấn guitar trong tầm 5tr - 10tr","content":"qwe"},
    {"username":"Hoang Manh Cuong","type":"Cầu lông","topic":"Tổ chức trận đấu tập","content":"qwe"},
    {"username":"Hoang Nam","type":"Đọc sách","topic":"Cách để trở thành người tri thức","content":"qwe"},
    {"username":"Hoang Diep","type":"Nhảy","topic":"Cách nhảy Hip-Hop","content":"qwe"},
    {"username":"Nguyen Thi Nguyen","type":"Bóng chuyền","topic":"Chia sẻ kiến thức thi đấu","content":"qwe"},
    {"username":"Nguyen Thi Thuy","type":"Cầu lông","topic":"Cách để đánh cầu lông một cách chuyên nghiệp","content":"qwe"},
    {"username":"Hoang Thien Phu","type":"Bóng đá","topic":"Chia sẻ địa điểm sân bóng đá tốt và rẻ","content":"qwe"},
    {"username":"Nguyen Thi Kim ngan","type":"Esport","topic":"Thông báo đợt tuyển thành viên CLB ESPORT","content":"qwe"},
    {"username":"Nguyen Hoa Vuong","type":"Kĩ năng","topic":"Vì sao chúng ta ngại trước đám đông ?","content":"qwe"},
    {"username":"Tran Bao Linh","type":"Kĩ năng","topic":"Làm chủ kĩ năng sáng tạo","content":"qwe"},
    {"username":"Nguyen Phuong Thao","type":"Guitar","topic":"Tổ chức lengend guitar university","content":"qwe"},
    {"username":"Ho Xuan Tuan Anh","type":"Cầu lông","topic":"Không ngán một ai","content":"qwe"},
    {"username":"Lê Tuấn Anh","type":"Kĩ năng","topic":"Chưa hề ngần ngại","content":"qwe"},
    {"username":"Nguyễn Chơn Uy","type":"Lập Trình","topic":"Chúa tể lập trình","content":"qwe"},
    {"username":"Nguyễn Phương Dung","type":"Hand in hand","topic":"Giúp người là giúp chình mình","content":"qwe"},
    {"username":"Đặng Ngọc Nghĩa","type":"Đọc sách","topic":"Kiến thức là kho tàng quý giá nhất","content":"qwe"},
    {"username":"Nguyễn Trường Sơn","type":"Bóng chuyền","topic":"Đam mê những giải đấu lớn","content":"qwe"},
    {"username":"Phạm Anh Tuấn","type":"Esport","topic":"Chỉ cần có đam mê thì mọi thứ sẽ oke","content":"qwe"},
    {"username":"Bùi Đình Thông","type":"Bóng đá","topic":"Đôi chân sinh ra là để ghi bàn","content":"qwe"},
    {"username":"Nguyễn Thị Phương Thảo","type":"Lập trình","topic":"Không có gì cản bước được mình code web","content":"qwe"},
    {"username":"Đặng Bá Chí","type":"Bóng đá","topic":"Sân cỏ này là sân chơi của tôi","content":"qwe"},
    {"username":"Nguyễn Thành Công","type":"Kĩ năng","topic":"Mọi thứ nhỏ nhặt ta có đều là kĩ năng sống","content":"qwe"},
    {"username":"Tống Chính Chung","type":"Hand in hand","topic":"Những trái tim ấm áp sát gần nhau","content":"qwe"},
    {"username":"Lê Văn Cường","type":"Đọc sách","topic":"Từng trang sách là từng thế giới mới","content":"qwe"},
    {"username":"Nguyễn Đại Cường","type":"Cầu lông","topic":"Cây vợt vàng kết liễu","content":"qwe"},
    {"username":"Nguyễn Phương Duyên","type":"Esport","topic":"Chưa biết sợ là gì","content":"qwe"},
    {"username":"Lê Thị Thùy Duyên","type":"Guitar","topic":"Từng phím đàn đưa ta quyện theo dòng cảm xúc","content":"qwe"},
    {"username":"Nguyễn Ngọc Diệp","type":"Đọc sách","topic":"Thích sự lãng mạn mà từng dòng chữ viết lên","content":"qwe"},
    {"username":"Nguyễn Thế Anh","type":"Guitar","topic":"Yêu cây đàn từ lần đầu nhìn thấy nó","content":"qwe"},
    {"username":"Nguyễn Đình Anh","type":"Bóng chuyền","topic":"đưa cả đội đến với chiến thắng","content":"qwe"},
    {"username":"Đinh Ngọc Anh","type":"Lập trình","topic":"Tạo ra cái mới là niềm đam mê","content":"qwe"},
    {"username":"Nguyễn Chế Bản","type":"Bóng chuyền","topic":"Những pha lật ngược cực gắt","content":"qwe"},
    {"username":"Tạ Quang Bảo","type":"Esport","topic":"Cú đêm sống giờ mĩ","content":"qwe"},
    {"username":"Nguyễn Tiến Dũng","type":"Nhảy","topic":"Tung tăng trên nhịp nhạc","content":"qwe"},
    {"username":"Trần Thị Phương Chi","type":"Hand in Hand","topic":"Trao yêu thương để nhận lại yêu thương","content":"qwe"},
    {"username":"Trần Quang Phú","type":"Lập trình","topic":"Đam mê từ nhỏ cơ","content":"qwe"},
    {"username":"Nguyễn Hồng An","type":"Cầu lông","topic":"Muốn thành công phải đánh cầu lông","content":"qwe"},
    {"username":"Lê Thị Mỹ Xinh","type":"Esport","topic":"Không tìm thấy điểm dừng","content":"qwe"},
    {"username":"Nguyễn Phương Ly","type":"Nhảy","topic":"Quẩy không ngừng nghỉ","content":"qwe"},
    {"username":"Đặng Văn Minh","type":"Đọc sách","topic":"Sách là người bạn tri kỉ","content":"qwe"},
    {"username":"Nguyễn Ngọc Thanh","type":"Guitar","topic":"Hòa vào đám đông","content":"qwe"},
    {"username":"Hồ Văn Sol","type":"Bóng chuyền","topic":"Đôi tay vàng vẩy bóng","content":"qwe"},
    {"username":"Phạm Tuyết Nhi","type":"Bóng đá","topic":"Kiến tạo những bàn thắng","content":"qwe"},
    {"username":"Nguyễn Viết Cương","type":"Kĩ năng","topic":"Tự tin có thừa khi thời cơ đến","content":"qwe"},
    {"username":"Tống Quế Anh","type":"Guitar","topic":"Vẩy đàn căng như vẩy rau","content":"qwe"}
]`);

    //"username":"Nguyen Phuong Tay","type":"Guitar","topic":"Tuyển thành viên CLB cầu lông","content":"qwe"
    //chinh lai cai noi dung topic tu line 13
localStorage.setItem("data", JSON.stringify(topics));